### ISSUE TITLE
derived fields can break custom mutations

### ISSUE THREAD

**Issue by edclement** [mattbretl/postgraphile-plugin-derived-field#1]
First, thanks for the awesome plugin. I'm running into an issue where the derived fields break the return payload for custom mutations. The schema that is generated states that the mutation return payload can include the derived field but if you include the derive field in the field list for the return payload, I end up with an error being thrown similar to :
`Error: Cannot query field "<DERIVED_FIELD_NAME>" on type "<TYPE>"`

The example code at https://www.graphile.org/postgraphile/custom-mutations/ will show the same issue.

**Comment by mattbretl** [comment]
I haven't been able to reproduce this. Starting from the [forum_example](https://github.com/graphile/postgraphile/tree/master/examples/forum) plus the following app code..
```js
app.use(
  postgraphile(
    "postgres://localhost:5432/forum_example",
    "forum_example",
    {
      graphiql: true,
      enableCors: true,
      pgDefaultRole: "forum_example_anonymous",
      jwtSecret: "keyboard_kitten",
      jwtPgTypeIdentifier: "forum_example.jwt_token",
      appendPlugins: [
        PostGraphileDerivedFieldPlugin
      ],
      graphileBuildOptions: {
        derivedFieldDefinitions: [
          {
            identifiers: [
              {
                columns: ["first_name", "last_name"]
              }
            ],
            inflect: () => `derivedName`,
            resolve: (first_name, last_name) => `${last_name} ${first_name}`
          }
        ]
      }
    }
  )
);
```
I'm able to execute this mutation:
```graphql
mutation {
  registerPerson(input:{
    firstName:"Alice"
    lastName:"Adams"
    email:"alice@example.com"
    password:"irf30r3#"
  }) {
    person {
      firstName
      lastName
      derivedName
    }
  }
}
```
Response:
```json
{
  "data": {
    "registerPerson": {
      "person": {
        "firstName": "Alice",
        "lastName": "Adams",
        "derivedName": "Adams Alice"
      }
    }
  }
}
```
Can you provide a minimal SQL schema, middleware config (or CLI string), and GraphQL query that reproduces the issue?

**Comment by edclement** [comment]
sorry for the delayed response, I've done a bunch of refactoring and updates to some of the other plugins I was using and this appears to be resolved. Thanks for looking into it though.
