### ISSUE TITLE
Consider adding File Upload example

### ISSUE THREAD

**Issue by Zireael** [mattbretl/postgraphile-plugin-derived-field#12]
Hi,
Sorry to trouble you.
The https://github.com/graphile-contrib/postgraphile-upload-example links to here recommending the plugin to be used for handling file upload.
> For a more robust solution, consider using something like postgraphile-plugin-derived-field to expose URLs through GraphQL instead of exposing the raw path/metadata.

Would it be possible to add a snippet example on how this should look like?
Thanks in advance for any advice!

**Comment by delianides** [comment]
@Zireael checkout the bottom of the README. There's a S3 example.

**Comment by mattbretl** [comment]
:+1: What @Zireael said.

**Comment by mattbretl** [comment]
To clarify, this part of the upload-example README.. 

> If you're streaming file uploads to an object storage service such as S3, you can also use the derived field plugin to generate pre-signed URLs for clients.

..is just suggesting that you might want to use the derived-field plugin to return download URLs. The derived-field plugin won't help with the uploads.
